FROM php

# RUN apt-get update && apt-get install -y libmemcached-dev zlib1g-dev \
#     && pecl install memcached-2.2.0 \
#     && docker-php-ext-enable memcached

# RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

CMD ["php", "-a"]